/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./shared/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        // Poppins Font
        poppins: ["Poppins-Regular"],
        "poppins-light": ["Poppins-Light"],
        "poppins-medium": ["Poppins-Medium"],
        "poppins-semibold": ["Poppins-SemiBold"],
        "poppins-bold": ["Poppins-Bold"],

        // Supreme Fonts
        supreme: ["Supreme-Regular"],
        "supreme-light": ["Supreme-Light"],
        "supreme-medium": ["Supreme-Medium"],
        "supreme-semibold": ["Supreme-SemiBold"],
        "supreme-bold": ["Supreme-Bold"],
      },
      colors: {
        // Light theme
        primary: "#272ea7",
        textGray: "#8f90a4",
        primaryLight: "#1C2A46",
        primaryDark: "#19243A",
        secondary: "#3B568B",
        secondaryLight: "#FF8A5C",
        secondaryDark: "#E55529",
        accent: "#FF6B00",
        accentLight: "#6EE7B7",
        accentDark: "#059669",
        background: "#FFFFFF",
        surface: "#F8F9FA",
        surfaceVariant: "#F1F3F4",
        text: "#1F2937",
        textSecondary: "#6B7280",
        textTertiary: "#9CA3AF",
        border: "#E5E7EB",
        borderLight: "#F3F4F6",
        success: "#10B981",
        warning: "#F59E0B",
        error: "#EF4444",
        info: "#3B82F6",
      },
      spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        "2xl": 48,
        "3xl": 64,
        "4xl": 96,
        "5xl": 128,
      },

      fontSize: {
        xs: 12,
        sm: 14,
        base: 16,
        lg: 18,
        xl: 20,
        "2xl": 24,
        "3xl": 30,
        "4xl": 36,
        "5xl": 48,
      },
      lineHeight: {
        xs: 16,
        sm: 20,
        base: 24,
        lg: 28,
        xl: 32,
        "2xl": 36,
        "3xl": 40,
        "4xl": 44,
        "5xl": 56,
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0,0,0,0.05)",
        md: "0 2px 4px 0 rgba(0,0,0,0.10)",
        lg: "0 4px 8px 0 rgba(0,0,0,0.15)",
      },
    },
  },
  plugins: [],
};
